deployment:
  tasks:
    - export DEPLOYPATH=/home/farmylxl/public_html
    # Step 1: Copy project files, excluding .git and .cpanel.yml
    - rsync -av --exclude=".git" --exclude=".cpanel.yml" ./ $DEPLOYPATH/
    # Step 2: Move to the deployment path
    - cd $DEPLOYPATH
    # Step 3: Install Laravel dependencies
    - /bin/composer install --no-dev --optimize-autoloader
    # Step 4: Run Laravel commands
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
